version: '2.2'

services:
  #{REPOSITORYNAME}#:
    image: #{IMAGETAG}#
    ports:
      - "6601:80"
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.165.1/24